### ISSUE TITLE
전화번호를 찾는 정규식을 작성하세요

### ISSUE THREAD

**Issue by sooooo-an** [homerunball-FE/fe-quiz-handbook#10]
```
010-2222-3333
010 2222 3333
010.222.333
010-333-2222
02-111-2222
```

위의 번호를 전부 찾을 수 있는 정규표현식을 작성하세요

**Comment by ByeongGi** [comment]
<details>
  <summary>크찬</summary>
  
정규식 (\d{2,3})([.|-\s]{0,1})(\d{3,4})([.|-\s]{0,1})(\d{3,4})  
</details>

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div markdown="1">

```
^\d{2,3}[- .]\d{3,4}[- .]\d{3,4}$
```

</div>
</details>

**Comment by marklee0905** [comment]
<details>
<summary>마크</summary>
<div>

`^(\d{2,3})[-.\s](\d{3,4})[-.\s](\d{3,4})$`

</div>
</details>

**Comment by sooooo-an** [comment]
`\d{2,3}[-.\s]\d{3}[-.\s]\d{4}`
