### ISSUE TITLE
beforeunload, DOMContentLoaded 이벤트에 대해 설명해주세요.

### ISSUE THREAD

**Issue by ddunny** [homerunball-FE/fe-quiz-handbook#11]
beforeunload, DOMContentLoaded 는 자바스크립트의 이벤트입니다.  
이 두 이벤트의 특징과 사용 예를 말해주세요.

**Comment by ByeongGi** [comment]
<details>
  <summary>크찬</summary>
  
    1. beforeunload 
        현재 화면에서 벗어나려고 할떄( 새로고침, 네이게이팅, 창 닫기, 도큐먼트에서 완전히 벗어나는 행위)
        - 화면에서 벗어날시에 유저에게 이 페이지로부터 벗어날지 물어보는데 주로 활용
    2. DOMContentLoaded 
       기본 특성이 document 가 로딩되고서 dom 에 대한 파싱이 끝난 상태에서 호출되는데, 보통 파싱이 다 끝난 상태이니
       dom에 대한 이벤트를 거는 타이밍으로 사용된다.
</details>

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div>
- DOMContentLoaded 이벤트는 html만을 전부 읽고, DOM 트리를 완성하는 즉시 발생 <br/>
- beforeunload 이벤트는 사용자가 페이지를 떠날 때 발생 
</div>
</details>

**Comment by marklee0905** [comment]
<details>
<summary>마크</summary>
<div>
1. beforeunload는 페이지를 나갈때 발생하는 이벤트로, 새로고침 뒤로가기 등에 발생합니다~! 저는 인풋 입력중 페이지 닫기, 새로고침,뒤로가기 방지를 위해 사용했습니다~!      
<br/>

2. DOMContentLoaded는 잘 몰라서 알아보았는데요,   
브라우저가 HTML을 전부 읽고 DOM 트리를 완성하는 `즉시` 발생한다고 합니다.
</div>
</details>

**Comment by ddunny** [comment]
**정답**  
`DOMContentLoaded` – 브라우저가 HTML을 전부 읽고 DOM 트리를 완성하는 즉시 발생합니다. 이미지 파일(`<img>`)이나 스타일시트 등의 기타 자원은 기다리지 않습니다.

- DOM이 준비된 것을 확인한 후 원하는 DOM 노드를 찾아 핸들러를 등록해 인터페이스를 초기화할 때 사용

`beforeunload` – 사용자가 사이트를 떠나려 할 때, 변경되지 않은 사항들을 저장했는지 확인시켜줄 때
