### ISSUE TITLE
3주차 앵귤러, rxjs 퀴즈

### ISSUE THREAD

**Issue by wook95** [homerunball-FE/fe-quiz-handbook#12]
1. elementRef, contentRef, viewContainerRef에 대해 설명해주세요~!

2. EMPTY와 NEVER에 대해 설명해주세요 (rxjs)

**Comment by ByeongGi** [comment]
<details>
  <summary>크찬</summary>
  
    1. 번 답안
       - elementRef는 실제 dom에 대한 정보를 가진 랩퍼임
       - contentRef ? 이건 머지? => ComponentRef 인가?
       - viewContainerRef :  컴포넌트에 view를 붙이거나 떠거나 할때 쓰는 일종의 컨테이너(담는 그릇)에 추상적인 랩퍼
                                         view 붙일떄 형제 단위에서 attach 시킨다. 
       
    2. 번 답안
       EMPTY : stream완전히 완료시킴 , 
       NEVER: 잠깐 현재 stream을 Pause 시키지만 , 완전히 완료되지 않음.

</details>



@wook95 
contentRef  머예요? 처음 보는녀석인데?

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div>
- elementRef: 뷰를 감싸는 네이티브 엘리먼츠로 DOM을 뜻한다  <br/>
- contentRef: 
- viewContainerRef: 하나 이상의 뷰를 연결할 수 있는 컨테이너로 모든 DOM 엘리먼츠는 view container로 사용가능하다 <br/>
- EMPTY: 빈값으로 스크림 연결 (complete O) <br/>
- NEVER: 아래의 코드 실행 X (complete X) <br/>
</div>
</details>

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div markdown="1">
1.

**ElementRef**  
엘리먼트를 나타내는 객체
`ElementRef` 를 사용해서 DOM을 직접 조작하면 XSS 공격에 취약해지므로, renerer2를 사용해서 DOM을 안전하게 조작하기

**ViewContainerRef**
하나 이상의 뷰를 연결할 수 있는 컨테이너

- DOM element는 View Container로 사용할 수 있다.
    - Angular가 엘리먼트 내부에 뷰를 삽입하는게 아니라 뷰 컨테이너에 바인딩 된 엘리먼트 뒤에 뷰를 추가한다. (router-outlet이 컴포넌트를 삽입하는 방식과 유사)

contentRef 는 모르겟습니당.!


2.

EMPTY: next 출력 X / completed 출력 O  
NEVER: next 출력 X / completed 출력 X  

```jsx
EMPTY.subscribe(x => {
  console.log('Empty Emit'); //This never fires. 
}, 
null, 
() => {
  console.log('Empty Complete'); //This does. 
});
```

```jsx
NEVER.subscribe(x => {
  console.log('Never Emit'); //This never fires. 
}, 
null, 
() => {
  console.log('Never Complete'); //This never fires. 
});
```
</div>
</details>
