### ISSUE TITLE
If 라는 타이핑을 작성해주세요.(타입스크립트)

### ISSUE THREAD

**Issue by ByeongGi** [homerunball-FE/fe-quiz-handbook#13]
조건 C, 참일 때 반환하는 타입 T, 거짓일 때 반환하는 타입 F를 받는 타입 If를 구현하세요. 
C는 true 또는 false이고, T와 F는 아무 타입입니다. 
(Conditional 타입을 이용하는 방식으로 하시면 됩니다.)

type A = If<true, 'a', 'b'>  // expected to be 'a'
type B = If<false, 'a', 'b'> // expected to be 'b'

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div markdown="1">
문제를 이해하기 사알짝 어려웠어유 크찬이 의도한 정답인지 모르겠네영

```
type If<C, T, F> = C extends true ?  T : F
```

</div>
</details>

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div markdown="1">
true, false는 값이기 때문에, 문제에서 의도하시는 바가 진행될 수 없었어요.  
 
typescript 공식문서를 보면 C는 타입 그자체여야 하는 것으로 보였슴당. string, number, interface ...  

제가 잘못 아는 걸 수 있으니 낼 풀이부탁드려요우~~~~

type If<C, T, F> = C extends boolean ? T : F;

type A = If<false, 'a', 'b'> // expected to be 'a'
type B = If<'false', 'a', 'b'> // expected to be 'b'

- 위와 같이 코드를 변경하면 expected 대로 되었음

</div>
</details>

**Comment by marklee0905** [comment]
<details>
<summary>마크
</summary
<div>
  type IF<C,T,F> =  any extends C? T:F
</div>
</details>

**Comment by ByeongGi** [comment]
정답)
type Bool  = true | false;
type If<C extends Bool,T, F> = C extends Bool ? T : F;

conditional에 boolean으로 타입 제한만 해도 모두 맞습니다.(쑤,로라 정답)
