### ISSUE TITLE
[Angular] 모듈에서 여러개의 서비스가 중복되어 등록되는 것을 막는 방법은?

### ISSUE THREAD

**Issue by sooooo-an** [homerunball-FE/fe-quiz-handbook#14]

**Comment by ByeongGi** [comment]
<details>
  <summary>크찬</summary>
  
   1. @Injectable 데코레이터의 providedIn옵션을 root 로 설정, 글로벌로 서비스 하나만 생성됨
  
   2. 모듈에 forRoot static 메서드를 만들고, 거기서 Module과 Providers(서비스들)을 넘겨주도록 하는 방법
</details>

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div>
싱글톤을 유지해야 할 서비스는 <br>
1. @Injectable({ providedIn: ‘root’ })로 사용한다.  <br>
2. @NgModule 메소드인 static forRoot() 사용한다.

</div>
</details>

**Comment by wook95** [comment]
<details>
<summary>마크</summary>
<div>
1. 컴포넌트별로 등록한다
2. root로 선언한다
</div>
</details>

**Comment by sooooo-an** [comment]
[https://angular.io/guide/singleton-services](https://angular.io/guide/singleton-services) 

모듈에 provider와 declarations을 정의한 뒤에, 여러개의 기능모듈을 로딩하면, 서비스의 등록이 중복되곤한다. 결과적으로 여러개 서비스의 인스턴스가 생겨나 더이상 싱글톤이 아니게 된다. 

이것을 방지하는 방법은, 

- 모듈에 서비스를 등록하는 대신, providedIn syntax를 사용한다
- 모듈 안에서 서비스를 분리해라
- forRoot, forChild 메서드로 정의해라
