### ISSUE TITLE
다음 자료형 중에 자료 순회시에 순서 보장을 하는 자료형을 모두 고르시오 ? (자바스크립트)

### ISSUE THREAD

**Issue by ByeongGi** [homerunball-FE/fe-quiz-handbook#15]
1. Array
2. Map
3. Object 리터럴
4. Set

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div>
2, 4
</div>
</details>

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div markdown="1">
1, 2, 4
</div>
</details>

**Comment by wook95** [comment]
<details>
<summary>마크</summary>
<div>1번 2번이요~!</div>
</details>
