### ISSUE TITLE
reflow, repaint에 대해서 설명해주세요.

### ISSUE THREAD

**Issue by ddunny** [homerunball-FE/fe-quiz-handbook#16]
1. reflow의 특징 / 최소화하기 위한 방법  
2. repaint의 특징 / 최소화하기 위한 방법  

위 두 질문에 대한 답을 작성해주세요.

**Comment by ByeongGi** [comment]
<details>
  <summary>크찬</summary>
   1. reflow
      ui 요소들의 크기나 위치 변경되면 그에 영향을 받는 노드들에 대한 연산 작업을 말한다.
      ( dom 엘리멘트의 추가, 삭제, 사이즈 변경 등- 전체적인 레이아웃에 연산이 필요한 작업이 발생할 경우)
      => 돔 요소의 추가 삭제 크기 변경이 빈번하게 일어나게 하지 않는다.
      
   2. repaint
      reflow가 요소들의  수학적인 위치나 크기 연산을 주로 하는 반면, 
     그외에 연산이 필요하지 않은 부분은 repaint 만 일어난다.
     
     => 현대적인 모던 프론트 프레임 워크는 VDOM , 증분 DOM 방식으로 최대한 직접적인 UI 변경을
     최소화하고, 최대한 덜 렌더링하도록 하는 방식으로 발전함.
     - 가장 큰 전략은 DOM에 대한 변경 점이 발생할 경우 브라우져 렌더링 타이밍에 모두 모아서(배치 작업)한꺼번에 
       가장 최근 변경점에 대해서만 DOM 직접 반영시킴.
     
</details>

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div markdown="1">
- reflow: 렌더트리에 있는 각각의 노드들이 화면의 어디에 위치할 것인지를 계산하는 과정으로, 이를 줄이기 위해서는 css 요소인 position, width, height를 줄여야 한다 <br/>
- repaint: 눈에 보이는 픽셀을 그리는 과정으로, css 속성의 visibility, background-color, outline 등을 줄여야 한다. 
</div>
</details>

**Comment by wook95** [comment]
<details>
<summary>마크</summary>
<div>
리플로우는 레이아웃등이 바뀔때 일어나고  
리페인트는 변경된 요소를 그리는것 ..  

</div>
</details>

**Comment by ddunny** [comment]
**리플로우**: 생성된 DOM 노드의 레이아웃 수치(너비, 높이, 위치 등) 변경 시 영향 받은 모든 노드의(자신, 자식, 부모, 조상(결국 모든 노드) ) 수치를 다시 계산하여(Recalculate), 렌더 트리를 재생성하는 과정  
**리페인팅**: Reflow 과정이 끝난 후 재 생성된 렌더 트리를 다시 그리는 과정

**리플로우 리페인팅 최적화 방법**
https://webclub.tistory.com/346
