### ISSUE TITLE
웹 워커에 대해 설명해주세요🌹

### ISSUE THREAD

**Issue by wook95** [homerunball-FE/fe-quiz-handbook#17]
웹 워커란?

**Comment by ByeongGi** [comment]
<details>
  <summary>크찬</summary>
  
    1. 웹 워커란 
    일반적으로 브라우져 상의 자바스크립트의 동작은 하나의 쓰레드(싱글 쓰레드))안에서 동작된다.
    자바의 경우 여러개의 쓰레드를 사용하여 많은 작업을 한꺼번에 병렬적으로 처리하거나 동작시키거나 하지만
    기존의 자바스크립트는 오로지 싱글 쓰레드 기반으로 프로그래밍이 가능했다. 
    이러한 불편한 배경으로 인해서 하나의 쓰레드에서 작업을 하는 것이 아니라 다른 쓰레드에서 작업을 진행시킬수 있도록
    하는 스펙의 필요성이 제기되었다. 
    거기서 웹 워커가 등장하게 된것이다. 웹 워커에 무거운 작업이나 연산을 맡겨놓고,  메인 쓰레드에서 연산이 끝난후에 
    결과만 받으면 된다. 메인 쓰레드에서 처리되는  UI 렌더링이나 자바스크립트의 작업에 영향을 최소시켜 보다 성능의 이점을 
    가질수 있다. 
     즉, 스타로 비유하면 미네랄을 추출하는 일꾼이 늘어난 것이다.  SCV 하나로만 처리하던 것을 여러 마리로 생산하여 처리할수 있게된 것이다. 
</details>

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div>
사용자 인터페이스를 방해하지 않고 백그라운드 스레드에서 스크립트를 실행하는데 사용함<br>
    - 웹 워커를 통해 개발자는 JavaScript 작업에 대한 새로운 실행 스레드를 만들 수 있음</div>
</details>

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div markdown="1">
스크립트 연산을 백그라운드 스레드에서 실행할 수 있는 기술로 워커 스레드를 사용하면 무거운 연산을 백그라운드 스레드에서 처리하여 UI 스레드등 주된 스레드가 느려지지 않고 동작할 수 있음. (워커스레드에서는 DOM 조작, window 일부 메서드와 속성 사용 불가)
</div>
</details>
