### ISSUE TITLE
ngrx를 사용할 때의 장점과 단점에 대해서 한가지씩 작성해주세요

### ISSUE THREAD

**Issue by sooooo-an** [homerunball-FE/fe-quiz-handbook#18]

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div markdown="1">

Ngrx를 사용하면 좋은 때

- 많은 컴포넌트와 서비스에서 상태에 접근하는 경우
    - 너무나 큰 프로젝트에서는 엄격한 사용이 중요하다
- 새로운 주소에 들어갈 때마다 상태를 사용해야 하는 경우
- 상태가 다양한 소스에 의해 영향을 받을 경우

Ngrx를 가치있게 사용하기

- 개발자도구로 디버깅이 쉽다
- 상태를 최대한 평평하게 유지하기

---

Ngrx를 사용할 필요가 없는 때

- 격리된 컴포넌트로 작은 웹 어플리케이션을 운영하는 경우
    - Ngrx를 사용하기 위한 코드를 짜는게 더 과할 수 있음
- 리액티브 접근법에 익숙하지 않은 경우
</div>
</details>

**Comment by wook95** [comment]
<details>
<summary>마크</summary>
<div>장점: 상태 스트림으로 관리해, 전역상태를 위한 다양한 옵저버블의 활용이 가능하다
</div>
<div>단점: 대형  프로젝트가 아니라면, 오버엔지니어링이 될 수도 있다 (복잡성이 있다)
</div>
</details>

**Comment by sooooo-an** [comment]
- 장점: 인터페이스 1개로 사용 가능, effect 사용가능, http 호출 수 줄일 수 있음 
- 단점: 첫 셋팅이 복잡함,
