### ISSUE TITLE
SSR 과 CSR 장단점을 설명해주세요. (1개로도 가능함)

### ISSUE THREAD

**Issue by ByeongGi** [homerunball-FE/fe-quiz-handbook#19]

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div markdown="1">
- SSR: 첫 렌더링 속도가 빠르다, 따로 웹서버를 둬야하는 경우가 있음, SEO 가능, 페이지마다 서버에서 html을 불러와야하는 이슈
- CSR: 첫 렝더링 속도가 느리다, (전체 다운로드 받아야됨), 페이지1개, SEO 각각페이지 적용 불가능, 화면 깜빡임 없음,
</div>
</details>

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div>
CSR 장점<br>
    - 네이티브 앱과 비슷한 빠른 인터렉션 구현 가능<br>
CSR 단점<br>
- 첫 페이지 로딩 속도가 서버 사이드 렌더링에 비해 다소 느림<br>
- 검색엔진최적화에 대한 추가 보완 작업이 필요함<br><br>

SSR 장점<br>
- 첫 페이지 로딩 속도가 CSR에 비해 빠름<br>

SSR 단점<br>
- 초기 로딩 이후 페이지 이동시 속도가 다소 느림<br><br>

</details>

**Comment by wook95** [comment]
<details>
<summary>마크</summary>
<div>ssr: 초기 로딩 속도가 빠름, seo에 유리</div>
<div>csr:네이티브처럼 매끄러운 웹 표현 가능/div>
</details>
