### ISSUE TITLE
도메인 로직과 비즈니스 로직에 대해서 설명해주세요 🎉

### ISSUE THREAD

**Issue by sooooo-an** [homerunball-FE/fe-quiz-handbook#21]

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div>
비즈니스 로직: 프로그램의 핵심 로직. 데이터가 생성되고 저장되고 수정되는지를 정의하는 것 
비즈니스 로직이 모델(도메인)에 가까울수록 서비스의 복잡도를 낮추는 효과를 얻을 수 있음  

비즈니스에 대한 의사결정을 하고있다면 도메인 로직이다.

개인적인 정리: 비즈니스 로직이 큰 범위이고 도메인 로직이 비즈니스 로직을 더 잘 관리하기 위한 하나의 방법론 같은 느낌이다.  



</details>

**Comment by wook95** [comment]
<details>
<summary>마크</summary>
<div>제가 조사한 바에 따르면 비즈니스 로직과 도메인 로직은 거의 유사한 용어로 쓰인다고 합니다~!</div>
<div>비즈니스 로직은, 해당 소프트웨어가 해결하고자 하는 문제를 다루는 코드입니다. 이와 반대되는 코드는 어플리케이션 코드로, 비즈니스로직에 필요한 프로그래밍적 코드입니다~!</div>

</details>
