### ISSUE TITLE
모노레포에 대해 설명해주세요👀

### ISSUE THREAD

**Issue by wook95** [homerunball-FE/fe-quiz-handbook#22]
장점 및 단점 등 !

**Comment by sooooo-an** [comment]
장점: 하나의 프로젝트에서 업데이트하면 다른 프로젝트에서도 전부 사용가능 
단점: 각각 다른 프로젝트에서 사용하는데 버전이 다르게 사용될수도있음 / 버전호환성의 문제

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
<div>

<img src="https://user-images.githubusercontent.com/44994243/208334665-8f087d11-7d2f-4936-8399-edce213cf978.png" />
https://d2.naver.com/helloworld/0923884

장점 : 쉬운 의존성 관리
단점: 개발 자율성의 멀티레포보다 떨어진다


</details>

**Comment by wook95** [comment]
모놀리스: 한개의 프로젝트, 한개의 VSC  
멀티레포(폴리레포): 여러개의 프로젝트 여러개의 VSC  
모노레포: 여러개의 프로젝트 한개의 VSC  

의존성 관리의 편안함: 공통으로 사용하는 의존성들은 공통 패키지에 넣으면 간편하다  
각 프로젝트를 따로따로 배포하지 않더라도, 로컬에서 바로 반영되므로 생산성이 올라간다, 또한 하나의 eslint,prettier등을 사용할 수 있으므로 코드의 일관성을 더 잘 지킬 수 있다.  


무분별한 의존성 연결 가능
의존성 연결이 쉽다 -> 과한 의존성
형상 관리 및 CI 속도 저하
리포지토리의 크기가 크기 때문

https://monorepo.tools/#polyrepo-concept
