### ISSUE TITLE
2.1 문제풀이

### ISSUE THREAD

**Issue by nayeonglee** [homerunball-FE/fe-quiz-handbook#25]
https://share.sourceacademy.org/lenasicp2

## 2.2
평면의 선분(line segment)을 표현하는 문제를 생각해 보자. 하나의 선분은 두 점의 쌍, 즉 시작점과 끝점의 쌍으로 표현할 수 있다. 두 점을 이용한 선분 표현을 정의하는 생성자 make_ segment와 선택자 start_segment 및 end_segment를 선언하라. 더 나아가서, 하나의 점 은좌표쌍,즉x 좌표성분과y 좌표성분의쌍으로표현할수있다.그러한표현을정의하는생 성자 make_point와 선택자 x_point 및 y_point를 정의하라. 마지막으로, 이 생성자들과 선택자들을 이용해서 선분의 중점(midpoint)을 계산하는 midpoint_segment 함수를 선언 하라. 이 함수는 선분 하나를 받고 그 선분의 중점을 돌려주어야 한다(여기서 중점은 그 좌표 성분들이 두 끝점 좌표성분들의 평균인 점이다). 그 함수를 시험해 보려면 점을 출력하는 수단 이 필요할 것이다. 다음이 그러한 용도의 함수이다.
```
function print_point(p) {
  return display("(" + stringify(x_point(p)) + ", " + stringify(y_point(p)) + ")");
}
```
> 풀이 방향
> print_point(calc_midPoint((2, 2), (2, 4))); 실행이 안됨....... 제가 무엇을 놓쳤을까요?

## 2.4
다음은 쌍의 또 다른 함수적 표현이다. 이 표현에서 임의의 객체 x와 y에 대한 head(pair(x,
y))가 x를 돌려주는지 확인하라.
```
function pair(x, y) { 
   return m => m(x, y);
}

function head(z) {
   return z((p, q) => p); 
}
```
tail은 어떻게 정의해야 할까? (힌트: 이것이 제대로 작동하는지 확인하는 데에는 §1.1.5의 치환 모형이 유용할 것이다.)
> 풀이 방향
> head(m => m('x', 'y')) 이후에 head 에서 뱉어내는 함수는 어떻게 적용시키는가????여러분??????

## 2.5
정수 a와 b의 쌍을 하나의 정수 2^a*3^b 으로 표현한다면, 음이 아닌 정수들의 쌍을 수치와 산술 연산만으로 표현할 수 있음을 보여라. 그리고 그런 표현을 정의하는 함수 pair, head, tail 을 정의하라.
> 풀이 방향
> pair 는 결과값이고 head 는 입력값 a, tail 은 입력값 b에 를 역산
> 거듭제곱의 결과를 역산하는 부분은 답지를 참고함

**Comment by nayeonglee** [comment]
> p.145 
프로그램은 데이 터에 관해 최소한의 가정만(주어진 과제를 수행하는 데 꼭 필요한 것만) 두어야 한다. 그와 함 께, ‘구체적(concrete)’ 데이터 표현을 해당 데이터를 사용하는 프로그램과는 독립적으로 정의해야 한다. 시스템의 이 두 부분 사이의 인터페이스는 선택자(selector)라고 부르는 함수와 생성자(constructor)라고 부르는 함수들의 집합으로 구성된다. 이 인터페이스는 구체적인 표 현을 이용해서 추상 데이터를 구현한다. 그럼 유리수를 다루는 함수들의 집합을 설계하는 예제 를 통해서 이 기법을 살펴보기로 하자.


관심사의 분리?

**Comment by ddunny** [comment]
앗 저번에 질문을 적으신걸 놓쳤슴다 @_@  

## 2.2 
공유해주신 링크에서 수정해봤어용! https://share.sourceacademy.org/laura211reply
- make_point로 감싸서 calc_midPoint로 넘기기  
- midpoint_segment 로 넘길 때는 make_segment로 감싸기
- 추가: 세미콜론 추가하기

2.4 는 안풀어서 모르게쑴다 ....!
