### ISSUE TITLE
A, B의 결과를 맞혀보세요.

### ISSUE THREAD

**Issue by ddunny** [homerunball-FE/fe-quiz-handbook#3]
```javascript
'hello' === new String('hello'); // A
new String('hello') === new String('hello'); // B
```

**Comment by ddunny** [comment]
<details>
<summary>
데릭이 노션에 준 정답
</summary>
<div markdown="1">
A: true<br>
B: false
</div>
</details>

**Comment by ddunny** [comment]
<details>
<summary>
수가 노션에 준 정답
</summary>
<div markdown="1">
A // false<br>
B // false
</div>
</details>

**Comment by ByeongGi** [comment]
<details>
  <summary>Christian </summary>

 > 

  > A: true

  > B: false
  
</details>

**Comment by wook95** [comment]
<details>
false
false
new 키워드를 통해 선언한 string의 경우 object이지 않을까 싶어서 false로 생각했습니다

<summary>
마크
</summary>
</details>

**Comment by ddunny** [comment]
**정답**  

false  
false

---

참고
https://stackoverflow.com/questions/14727044/what-is-the-difference-between-types-string-and-string  
https://stackoverflow.com/questions/25647680/why-does-new-stringhello-new-stringhello-evaluate-to-false
