### ISSUE TITLE
instanceof의 결과값이 true가 되도록 만들기

### ISSUE THREAD

**Issue by load28** [homerunball-FE/fe-quiz-handbook#5]
```javascript
function A() {}
function B() {}

const a = new A();
const b = new B();
```
코드가 위와 같을 때 `a instanceof b`의 결과 값이 true가 되도록 코드를 작성해주세요. (크롬 브라우저 환경)

**Comment by sooooo-an** [comment]
<details>
    <summary>soo 정답</summary>
    `A.prototype = new B();`
</details>

**Comment by wook95** [comment]
<details>

```jsx

function A() {
  this.__proto__ = new B();
}
function B() {
}

```

<summary>
마크
</summary>
</details>

**Comment by ddunny** [comment]
<details>
<summary>
로라
</summary>
<div markdown="1">
function A() {}
function B() {}

A.prototype = new B(); 

const a = new A();
const b = B;
</div>
</details>

**Comment by Swit-ChristianKim** [comment]
<details>
    <summary>크찬</summary>

//  프로토 타입 바꾸기

function A() {}
function B() {}

const a = new A();
const b = new B();
``a.__proto__ = b.__proto__ ``

</details>

**Comment by ddunny** [comment]
**정답**  

실행코드

```
function A() {}
function B() {}

A.prototype = new B(); 

const a = new A();
const b = new B();

console.log( a instanceof B ); // true
console.log( a instanceof b ); // Error: Right-hand side of 'instanceof' is not callable
```

https://stackblitz.com/edit/js-9sn2he?file=index.js

참고
https://runebook.dev/ko/docs/javascript/errors/invalid_right_hand_side_instanceof_operand
