### ISSUE TITLE
const, let에 대한 설명으로 옳은 것으로 빈칸을 채워주세요. 그리고 마지막 답변에 대한 이유에 대해서도 작성해주세요

### ISSUE THREAD

**Issue by sooooo-an** [homerunball-FE/fe-quiz-handbook#6]
`const`와 `let`은 (1. ES5/ 2. ES6)에서 새로 나온 개념으로, `const`는 (1. 상수/ 2. 변수)를 선언할 때 사용되며, `let은 (1. 상수/ 2. 변수)를 선언할 때 사용된다.  이 두가지는 (1. 블록/ 2. 함수)스코프를 가지며, 호이스팅이 (1. 일어난다 / 2. 일어나지 않는다) 
마지막 빈칸(호이스팅이 일어나거나, 일어나지 않는다)에 대해 생각한 이유에 대해 자신의 의견을 작성해주세요

**Comment by wook95** [comment]
<details>
<summary>마크
</summary>
<div>
1. es6
2. 상수
3. 변수

상수는 변하지 않는값, 변수는 변할 수 있는 값이다.
자바스크립트의 const는 재할당은 불가능 하지만, object형의 경우 프로퍼티의 변경은 가능하다.
object.freeze를 통해 프로퍼티의 변경을 막을 순 있지만 중첩객체의 경우 deep freeze가 필요하다.

4. 블록 스코프
5. 호이스팅된다.
6. let과 const로 선언한 변수들을 선언 전에 참조하려고 하면 참조 에러가 발생해, (temporary dead zone) 호이스팅이 일어나지 않는것 처럼 보이지만, 사실을 일어난다.

호이스팅이란 끌어올린다 라는 뜻이다.
var로 선언한 변수의 경우, 코드의 최상단으로 끌어올려진 것 처럼 동작해서 이러한 이름이 붙었다.
 자바스크립트 코드가 평가될 때 모든 변수들을 조사해 렉시컬 환경에 등록하는데,  var의 경우 선언과 초기화가 동시에 일어나 undefined로 초기화 되고, let의 경우 선언만 해 렉시컬 환경에 등록해 놓는다.
 따라서 var로 선언된 변수들은 초기화가 일어낫기에 변수 선언문 이 전에도 참조할 수 있고, let은 참조할 순 없지만, 최초 렉시컬 환경에 등록된 점을 보아 호이스팅이 일어난다고 생각할 수 있다.

</div>
<details>

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
- ES6   
- 상수  
- 변수  
- 블록  
- 일어나지 않는다  

---

var는 호이스팅이 되기 때문에 먼저 할당을 한후 선언을 하는게 가능하지만, let/const의 경우에는 이게 불가능하다.  
이는 호이스팅이 가능하고 불가능한 특징으로 발생한다.  

```
test = 'a';
var test;
console.log(test); // a
```

```
test2 = 'a';
let test2;
console.log(test2); // Error: Cannot access 'test2' before initialization
```
</details>

**Comment by ByeongGi** [comment]
<details>
  <summary>크찬</summary>
  
  1. ES6
  2. 상수
  3. 변수
  4. 블록
  5. 호이스팅된다. 
  -> 다만 글로벌 레벨에서 호이스팅만 되지 않는다. 하지만 let도 블록구문 안에서도 호이스팅이 발생가능하다.
</details>

**Comment by sooooo-an** [comment]
const와 let은  **ES6**에서 새로 나온 개념으로, const는 **1. 상수**를 선언할 때 사용되며, `let은  **2. 변수**를 선언할 때 사용된다. 이 두가지는 **1. 블록**스코프를 가지며, 호이스팅이 **1. 일어난다**

마지막 빈칸(호이스팅이 일어나거나, 일어나지 않는다)에 대해 생각한 이유에 대해 자신의 의견을 작성해주세요
