### ISSUE TITLE
2주차 타입스크립트, HTML, 앵귤러 퀴즈

### ISSUE THREAD

**Issue by wook95** [homerunball-FE/fe-quiz-handbook#7]
1. 타입스크립트의 타입으로 아래와 같이 함수를 오버로드 할 수 있을까요~?
```jsx
const add = (a:number, b: number) => {
  return a+b;
}

const add = (a:string , b: string) => {
  return a+b;
}
```

2. ul태그는 몇개가 필요할까요?
![스크린샷 2022-11-14 오후 1 39 27 1](https://user-images.githubusercontent.com/80494742/201600339-541e3808-fc01-4591-b74e-17764e725f90.png)

3. 앵귤러에서 zone의 역할에 대해 설명해주세요~!

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
1. function 형으로는 가능하고 arrow function 으로는 불가능 (https://lakelouise.tistory.com/194)<br>   
2. 짜기 나름일 것 같습니다. 최소 1개!<br>   
3. 비동기 작업(setTimeOut, 서버통신 등)을 위한 실행 컨텍스트 
</details>

**Comment by ByeongGi** [comment]
<details>
  <summary>크찬</summary>
  
  1. 불가능 
  2. 1개 
  3. zone
  -> js 의 모든 네이티브 이벤트를 몽키패칭하는 방식으로 별도의 감지 시키는 코드를 따로 작성없이도  앱 상태의 변경을 자동으로 시켜줍니다.  
</details>

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div markdown="1">
1. 있습니다 <br/>
2. ul태그 1개 / li태그 12개 <br/>
3. 시작 시 Angular는 브라우저 기능인 addEventListener와 같은 여러 하위 수준의 브라우저 API를 패치하는데,  새로운 버전의 addEventListener는 기존에 등록되어있는 콜백함수를 호출할 뿐만 아니라 Angular의 변경 감지 함수를 실행하고, UI를 다시 렌더링한다. 여기서 Angular와 함께 제공되는 zone.js라고 불리는 라이브러리를 통해서 하위 수준의 브라우저 API를 패치한다. zone.js의 제일 큰 약점은 zone.js가 지원하지 않는 API의 경우에는 수동으로 변경감지를 시켜주어야한다 
</div>
</details>

**Comment by wook95** [comment]
1. 타입스크립트의 타입으로 아래와 같이 함수를 오버로드 할 수 있을까요~?

동일한 이름에 매개변수만 다른 여러 버전의 함수 ->  '함수 오버로딩'
타입스크립트에서는 타입과 런타임의 동작이 무관하기 때문에, 함수 오버로딩은 불가능 합니다.

```ts
function add(a: number, b: number) { return a + b; } // 중복된 함수입니다.

function add(a: string, b: string) { return a + b; } // 중복된 함수입니다.
```

타입스크립트가 함수 오버로딩 기능을 지원하기는 하지만, 온전히 타입 수준에서만 동작합니다.
하나의 함수에 대해 여러 개의 선언문을 작성할 수 있지만, 구현체는 오직 하나 입니다.

```ts
function add(a: number, b: number): number
function add(a: string, b: string): string

function add(a, b) { return a + b }

const three = add(1, 2)       // 타입이 number
const twelve = add('1', '2')  // 타입이 string
```
effective typescript


2. ul태그는 몇개가 필요할까?
![[스크린샷 2022-11-14 오후 1.39.27.png]]
https://aoa.gitbook.io/skymimo/aoa-2018/tips/dl


레이아웃을 위해 <ul>을 단순 반복하게 되면,
스크린리더 사용자들은 전체가 몇 개의 리스트로 구성되어 있는지,
페이지를 어떻게 탐색해야 하는지 알 수가 없게 됩니다.
그렇기 때문에 한 개의 리스트는 한 개의 <ul>로 사용해야 합니다. (웹 접근성)


3. 앵귤러에서 zone.js의 역할에 대해 설명하기

zone.js는 비동기 실행을 하나의 컨텍스트(zone)으로 다루기 위해 개발되었다.  
이 zone을 이용해 앵귤러는 비동기 요청을 모두 zone의 함수로 몽키패치해서  
언제 데이터의 변화가 일어난지 알 수 있게 만들어준다.
