### ISSUE TITLE
Arrow 함수와 일반 함수의 생성자 호출시 예상되는 동작 결과를 설명하세요.

### ISSUE THREAD

**Issue by Swit-ChristianKim** [homerunball-FE/fe-quiz-handbook#8]
Arrow 함수와 일반 함수의 생성자 호출시 예상되는 동작 결과를 설명하세요. 
```ts
const a = () => {}
const b = function B() {}

new a();
new b();
```

**Comment by marklee0905** [comment]
<details>
  <summary>마크</summary>
  <div>
  화살표 함수의 경우.. 생성자 함수가 없어 오류가 날 것 같고, 
  함수 선언문의 경우 정상 실행 될 것 같슴다
  </div>
</details>

**Comment by wook95** [comment]
<details>
  <summary>마크</summary>
  <div>
  화살표 함수의 경우.. 생성자 함수가 없어 오류가 날 것 같고, 
  함수 선언문의 경우 정상 실행 될 것 같슴다
  </div>
</details>

**Comment by ddunny** [comment]
<details>
<summary>로라</summary>
console.log를 찍었다는 가정하에...<br>
new a() => arrow function은 new를 사용할 수 없으므로 오류 발생<br>
new b() => 함수 출력

</details>

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div markdown="1">
Arrow 함수의 경우 프로토타입이 없기 떄문에 생성자가 생성되지 않을 거 같아요~ (에러나지 않을까?)
일반 함수의 경우 생성자가 생성 및 프로토타입 연결
</div>
</details>

**Comment by ByeongGi** [comment]
정답
- arrow 함수는 스펙상 일반 함수와 다르게 생성자가 없습니다.
