### ISSUE TITLE
코드가 동작하도록 수정해주세요.

### ISSUE THREAD

**Issue by ddunny** [homerunball-FE/fe-quiz-handbook#9]
```typescript
import { timer, forkJoin } from 'rxjs';

const timerOne$ = timer(1000, 4000);
const timerTwo$ = timer(2000, 4000);
const timerThree$ = timer(3000, 4000);

forkJoin([timerOne$, timerTwo$, timerThree$]).subscribe(
  ([timerValOne, timerValTwo, timerValThree]) => {

    //*****************
    console.log(
      `Timer One Latest: ${timerValOne},
     Timer Two Latest: ${timerValTwo},
     Timer Three Latest: ${timerValThree}`
    );  
    // *******************
  }
);

```

console.log()의 내용이 나오도록 코드를 수정해주세요.

**Comment by ByeongGi** [comment]
<details>
  <summary>크찬</summary>
    ``ts
    
    import { timer, forkJoin, first } from 'rxjs';
    
    const timerOne$ = timer(1000, 4000).pipe(first());
    const timerTwo$ = timer(2000, 4000).pipe(first());
    const timerThree$ = timer(3000, 4000).pipe(first());
    
    forkJoin([timerOne$, timerTwo$, timerThree$]).subscribe(
      ([timerValOne, timerValTwo, timerValThree]) => {
        //*****************
        console.log(
          `Timer One Latest: ${timerValOne},
         Timer Two Latest: ${timerValTwo},
         Timer Three Latest: ${timerValThree}`
        );
        // *******************
      }
    );
   ``
</details>

**Comment by wook95** [comment]
<details>
<summary>
마크
</summary>
      Timer One Latest: 0,
     Timer Two Latest: 0,
     Timer Three Latest: 0
</details>

**Comment by sooooo-an** [comment]
<details>
<summary>쑤</summary>
<div markdown="1">

```
const timerOne$ = timer(1000, 4000).pipe(take(1));
const timerTwo$ = timer(2000, 4000).pipe(take(1));
const timerThree$ = timer(3000, 4000).pipe(take(1));
```

</div>
</details>

**Comment by ddunny** [comment]
**정답**  
- 타이머 옵저버에 complete 시키는 오퍼레이터를 추가하거나, forkJoin을 combineLatest 오퍼레이터로 변경하기

> forkJoin의 특성을 이해하기 위한 문제!
